import type { RankingBoard, SocialCourse } from "./types";

// 커뮤니티(소셜) 코스 시드 데이터 — 실제 사용자가 만든 예산 코스를 모사
export const SOCIAL_COURSES: SocialCourse[] = [
  {
    id: "c-seongsu-3",
    title: "3만원 성수 데이트 코스",
    budget: 30000,
    area: "성수",
    companion: "couple",
    author: { name: "지우", handle: "@jiwoo", avatar: "🧃" },
    cover: "sunset",
    stops: [
      { name: "어니언 성수", cost: 7000, category: "cafe", emoji: "🥐" },
      { name: "성수 브랜드 팝업존", cost: 0, category: "culture", emoji: "🎁" },
      { name: "성수 수제버거", cost: 13000, category: "food", emoji: "🍔" },
      { name: "서울숲 산책", cost: 0, category: "walk", emoji: "🌳" },
    ],
    likes: 1284,
    saves: 932,
    rating: 4.9,
    reviews: 211,
    totalCost: 20000,
    tags: ["데이트", "팝업", "감성"],
    createdLabel: "3일 전",
  },
  {
    id: "c-hangang-1",
    title: "1만원으로 노는 한강 하루",
    budget: 10000,
    area: "한강",
    companion: "friend",
    author: { name: "민서", handle: "@minseo", avatar: "🌊" },
    cover: "river",
    stops: [
      { name: "한강 자전거 대여", cost: 3000, category: "activity", emoji: "🚲" },
      { name: "한강 편의점 라면", cost: 6000, category: "food", emoji: "🍜" },
      { name: "뚝섬한강공원", cost: 0, category: "walk", emoji: "🌅" },
    ],
    likes: 2041,
    saves: 1588,
    rating: 4.8,
    reviews: 333,
    totalCost: 9000,
    tags: ["가성비", "한강", "노을"],
    createdLabel: "1일 전",
  },
  {
    id: "c-yeonnam-2",
    title: "2만원 연남 혼놀 코스",
    budget: 20000,
    area: "연남·홍대",
    companion: "solo",
    author: { name: "하늘", handle: "@haneul", avatar: "🪐" },
    cover: "lavender",
    stops: [
      { name: "연남 베이글 맛집", cost: 8000, category: "dessert", emoji: "🥯" },
      { name: "연남 감성카페", cost: 6500, category: "cafe", emoji: "☕" },
      { name: "연트럴파크 산책", cost: 0, category: "walk", emoji: "🌿" },
    ],
    likes: 1675,
    saves: 1402,
    rating: 4.9,
    reviews: 289,
    totalCost: 14500,
    tags: ["혼놀", "카페", "산책"],
    createdLabel: "2일 전",
  },
  {
    id: "c-bukchon-1",
    title: "2만원 북촌 전시 데이트",
    budget: 20000,
    area: "북촌·종로",
    companion: "couple",
    author: { name: "서연", handle: "@seoyeon", avatar: "🎨" },
    cover: "stone",
    stops: [
      { name: "국립현대미술관 서울", cost: 4000, category: "culture", emoji: "🖼️" },
      { name: "익선동 한옥카페", cost: 7500, category: "cafe", emoji: "🍵" },
      { name: "북촌한옥마을", cost: 0, category: "walk", emoji: "🏯" },
    ],
    likes: 1130,
    saves: 870,
    rating: 4.8,
    reviews: 176,
    totalCost: 11500,
    tags: ["전시", "한옥", "데이트"],
    createdLabel: "4일 전",
  },
  {
    id: "c-seoul-5",
    title: "5만원 서울 데이트 풀코스",
    budget: 50000,
    area: "신사·압구정",
    companion: "couple",
    author: { name: "도현", handle: "@dohyun", avatar: "🌃" },
    cover: "night",
    stops: [
      { name: "압구정 파스타", cost: 16000, category: "food", emoji: "🍝" },
      { name: "신사 미디어아트 전시", cost: 12000, category: "culture", emoji: "🌌" },
      { name: "가로수길 디저트카페", cost: 9000, category: "cafe", emoji: "🧁" },
      { name: "압구정 루프탑바", cost: 18000, category: "bar", emoji: "🌃" },
    ],
    likes: 980,
    saves: 742,
    rating: 4.9,
    reviews: 158,
    totalCost: 55000,
    tags: ["데이트", "야경", "분위기"],
    createdLabel: "6일 전",
  },
  {
    id: "c-jamsil-4",
    title: "4만원 잠실 친구 나들이",
    budget: 40000,
    area: "잠실·송파",
    companion: "friend",
    author: { name: "유진", handle: "@yujin", avatar: "🎢" },
    cover: "mint",
    stops: [
      { name: "롯데월드 어드벤처", cost: 30000, category: "activity", emoji: "🎢" },
      { name: "방이동 맛집거리", cost: 12000, category: "food", emoji: "🍲" },
      { name: "석촌호수 산책", cost: 0, category: "walk", emoji: "🦢" },
    ],
    likes: 1342,
    saves: 1011,
    rating: 4.7,
    reviews: 220,
    totalCost: 42000,
    tags: ["놀이공원", "친구", "액티비티"],
    createdLabel: "5일 전",
  },
  {
    id: "c-hongdae-2",
    title: "2만원 홍대 액티비티 데이",
    budget: 20000,
    area: "연남·홍대",
    companion: "friend",
    author: { name: "준호", handle: "@junho", avatar: "🔓" },
    cover: "lavender",
    stops: [
      { name: "홍대 방탈출 카페", cost: 22000, category: "activity", emoji: "🔓" },
      { name: "연트럴파크 산책", cost: 0, category: "walk", emoji: "🌿" },
    ],
    likes: 760,
    saves: 540,
    rating: 4.6,
    reviews: 98,
    totalCost: 22000,
    tags: ["방탈출", "친구", "액티비티"],
    createdLabel: "오늘",
  },
  {
    id: "c-hangang-3",
    title: "3만원 한강 피크닉 코스",
    budget: 30000,
    area: "한강",
    companion: "couple",
    author: { name: "예린", handle: "@yerin", avatar: "🧺" },
    cover: "river",
    stops: [
      { name: "한강뷰 카페", cost: 8500, category: "cafe", emoji: "🏙️" },
      { name: "한강 자전거 대여", cost: 3000, category: "activity", emoji: "🚲" },
      { name: "뚝섬한강공원", cost: 0, category: "walk", emoji: "🌅" },
      { name: "노들섬 무료 공연", cost: 0, category: "culture", emoji: "🎶" },
    ],
    likes: 1520,
    saves: 1220,
    rating: 4.9,
    reviews: 240,
    totalCost: 11500,
    tags: ["피크닉", "노을", "공연"],
    createdLabel: "2일 전",
  },
];

export function getSocialCourse(id: string): SocialCourse | undefined {
  return SOCIAL_COURSES.find((c) => c.id === id);
}

// 실데이터 랭킹 보드 (세그먼트별 만족도/평점 TOP)
export const RANKING_BOARDS: RankingBoard[] = [
  {
    id: "rb-female-solo-2",
    segment: "20대 여성 · 혼자 · 2만원 이하",
    metricLabel: "만족도",
    courses: [
      SOCIAL_COURSES.find((c) => c.id === "c-yeonnam-2")!,
      SOCIAL_COURSES.find((c) => c.id === "c-bukchon-1")!,
      SOCIAL_COURSES.find((c) => c.id === "c-hangang-1")!,
    ],
  },
  {
    id: "rb-couple-5",
    segment: "20대 커플 · 5만원 이하",
    metricLabel: "평균 평점",
    courses: [
      SOCIAL_COURSES.find((c) => c.id === "c-seoul-5")!,
      SOCIAL_COURSES.find((c) => c.id === "c-seongsu-3")!,
      SOCIAL_COURSES.find((c) => c.id === "c-hangang-3")!,
    ],
  },
];

export const COVER_GRADIENTS: Record<string, string> = {
  sunset: "from-[#FF8A5B] via-[#FF6F91] to-[#7C5CFF]",
  river: "from-[#43C6FF] via-[#2F6BFF] to-[#1E4FD9]",
  lavender: "from-[#A78BFA] via-[#7C5CFF] to-[#4F46E5]",
  stone: "from-[#9CA3AF] via-[#6B7280] to-[#374151]",
  night: "from-[#1E293B] via-[#312E81] to-[#0A0B0D]",
  mint: "from-[#34D399] via-[#10B981] to-[#0EA5A0]",
};
