import type { Place } from "./types";

// 데모용 큐레이션 데이터셋 (서울 핵심 상권).
// 실제 서비스에서는 장소/할인/팝업/혼잡도 API로 대체됩니다.
export const AREAS = ["성수", "연남·홍대", "한강", "북촌·종로", "신사·압구정", "잠실·송파"] as const;

export const PLACES: Place[] = [
  // ───────── 성수 ─────────
  {
    id: "sd-cafe-1",
    name: "어니언 성수",
    area: "성수",
    category: "cafe",
    cost: 7000,
    duration: 60,
    rating: 4.6,
    companions: ["solo", "friend", "couple"],
    vibes: ["trendy", "calm"],
    setting: "indoor",
    bestStart: 11,
    tags: ["인더스트리얼", "베이커리", "사진맛집"],
    signal: { crowd: "high" },
    blurb: "정미소를 개조한 성수 대표 베이커리 카페",
    emoji: "🥐",
  },
  {
    id: "sd-popup-1",
    name: "성수 브랜드 팝업존",
    area: "성수",
    category: "culture",
    cost: 0,
    duration: 50,
    rating: 4.4,
    companions: ["solo", "friend", "couple"],
    vibes: ["trendy", "culture"],
    setting: "indoor",
    bestStart: 13,
    tags: ["팝업스토어", "포토존", "굿즈"],
    signal: { popup: true, free: true, crowd: "mid" },
    blurb: "매주 바뀌는 브랜드 팝업, 입장 무료",
    emoji: "🎁",
  },
  {
    id: "sd-food-1",
    name: "성수 수제버거",
    area: "성수",
    category: "food",
    cost: 13000,
    duration: 60,
    rating: 4.5,
    companions: ["friend", "couple", "solo"],
    vibes: ["foodie", "trendy"],
    setting: "indoor",
    bestStart: 12,
    tags: ["수제버거", "혼밥가능"],
    blurb: "두툼한 패티의 성수 인기 버거집",
    emoji: "🍔",
  },
  {
    id: "sd-dessert-1",
    name: "도산분식 X 디저트바",
    area: "성수",
    category: "dessert",
    cost: 9000,
    duration: 40,
    rating: 4.3,
    companions: ["friend", "couple"],
    vibes: ["trendy", "foodie"],
    setting: "indoor",
    bestStart: 15,
    tags: ["디저트", "시즌메뉴"],
    signal: { discount: 15 },
    blurb: "지금 시즌 한정 메뉴 15% 할인 중",
    emoji: "🍰",
  },
  {
    id: "sd-walk-1",
    name: "서울숲 산책",
    area: "성수",
    category: "walk",
    cost: 0,
    duration: 50,
    rating: 4.7,
    companions: ["solo", "friend", "couple", "family"],
    vibes: ["calm", "active"],
    setting: "outdoor",
    bestStart: 16,
    tags: ["공원", "산책", "무료"],
    signal: { free: true, crowd: "low" },
    blurb: "도심 속 가장 여유로운 무료 산책 코스",
    emoji: "🌳",
  },
  {
    id: "sd-activity-1",
    name: "성수 도자기 원데이클래스",
    area: "성수",
    category: "activity",
    cost: 28000,
    duration: 90,
    rating: 4.6,
    companions: ["couple", "friend"],
    vibes: ["calm", "culture"],
    setting: "indoor",
    bestStart: 14,
    tags: ["클래스", "체험", "기념품"],
    blurb: "직접 만든 컵을 가져가는 인기 클래스",
    emoji: "🏺",
  },

  // ───────── 연남·홍대 ─────────
  {
    id: "yn-cafe-1",
    name: "연남 감성카페",
    area: "연남·홍대",
    category: "cafe",
    cost: 6500,
    duration: 55,
    rating: 4.4,
    companions: ["solo", "friend", "couple"],
    vibes: ["calm", "trendy"],
    setting: "indoor",
    bestStart: 11,
    tags: ["감성", "통창", "노트북"],
    signal: { discount: 10, crowd: "mid" },
    blurb: "지금 음료 10% 할인, 통창 자리 인기",
    emoji: "☕",
  },
  {
    id: "yn-walk-1",
    name: "연트럴파크 산책",
    area: "연남·홍대",
    category: "walk",
    cost: 0,
    duration: 40,
    rating: 4.5,
    companions: ["solo", "friend", "couple", "family"],
    vibes: ["calm", "active"],
    setting: "outdoor",
    bestStart: 17,
    tags: ["산책", "무료", "피크닉"],
    signal: { free: true },
    blurb: "경의선 숲길을 따라 걷는 무료 코스",
    emoji: "🌿",
  },
  {
    id: "yn-food-1",
    name: "홍대 화로구이",
    area: "연남·홍대",
    category: "food",
    cost: 15000,
    duration: 70,
    rating: 4.4,
    companions: ["friend", "couple"],
    vibes: ["foodie"],
    setting: "indoor",
    bestStart: 18,
    tags: ["고기", "가성비"],
    blurb: "가성비 좋은 1인분 화로구이",
    emoji: "🍖",
  },
  {
    id: "yn-activity-1",
    name: "홍대 방탈출 카페",
    area: "연남·홍대",
    category: "activity",
    cost: 22000,
    duration: 80,
    rating: 4.6,
    companions: ["friend", "couple"],
    vibes: ["active"],
    setting: "indoor",
    bestStart: 15,
    tags: ["방탈출", "액티비티"],
    signal: { crowd: "mid" },
    blurb: "난이도별 테마가 많은 인기 방탈출",
    emoji: "🔓",
  },
  {
    id: "yn-bar-1",
    name: "연남 칵테일바",
    area: "연남·홍대",
    category: "bar",
    cost: 14000,
    duration: 70,
    rating: 4.5,
    companions: ["couple", "friend"],
    vibes: ["trendy", "calm"],
    setting: "indoor",
    bestStart: 20,
    tags: ["칵테일", "무드"],
    blurb: "조용히 한 잔 하기 좋은 무드의 바",
    emoji: "🍸",
  },
  {
    id: "yn-dessert-1",
    name: "연남 베이글 맛집",
    area: "연남·홍대",
    category: "dessert",
    cost: 8000,
    duration: 40,
    rating: 4.3,
    companions: ["solo", "friend", "couple"],
    vibes: ["foodie", "trendy"],
    setting: "indoor",
    bestStart: 10,
    tags: ["베이글", "브런치"],
    blurb: "겉바속촉 수제 베이글",
    emoji: "🥯",
  },

  // ───────── 한강 ─────────
  {
    id: "hg-walk-1",
    name: "뚝섬한강공원",
    area: "한강",
    category: "walk",
    cost: 0,
    duration: 60,
    rating: 4.8,
    companions: ["solo", "friend", "couple", "family"],
    vibes: ["calm", "active"],
    setting: "outdoor",
    bestStart: 16,
    tags: ["한강", "피크닉", "무료", "노을"],
    signal: { free: true, crowd: "low" },
    blurb: "노을 맛집, 돗자리 펴고 쉬기 좋은 곳",
    emoji: "🌅",
  },
  {
    id: "hg-food-1",
    name: "한강 편의점 라면",
    area: "한강",
    category: "food",
    cost: 6000,
    duration: 40,
    rating: 4.2,
    companions: ["solo", "friend", "couple"],
    vibes: ["foodie", "calm"],
    setting: "outdoor",
    bestStart: 18,
    tags: ["라면", "야장", "가성비"],
    blurb: "한강에서 끓여 먹는 즉석 라면",
    emoji: "🍜",
  },
  {
    id: "hg-activity-1",
    name: "한강 자전거 대여",
    area: "한강",
    category: "activity",
    cost: 3000,
    duration: 60,
    rating: 4.6,
    companions: ["friend", "couple", "family"],
    vibes: ["active"],
    setting: "outdoor",
    bestStart: 15,
    tags: ["따릉이", "자전거", "가성비"],
    signal: { discount: 0 },
    blurb: "따릉이로 한강을 가로지르는 라이딩",
    emoji: "🚲",
  },
  {
    id: "hg-cafe-1",
    name: "한강뷰 카페",
    area: "한강",
    category: "cafe",
    cost: 8500,
    duration: 55,
    rating: 4.5,
    companions: ["couple", "friend"],
    vibes: ["calm", "trendy"],
    setting: "indoor",
    bestStart: 14,
    tags: ["뷰맛집", "통창"],
    blurb: "한강이 한눈에 들어오는 뷰 카페",
    emoji: "🏙️",
  },
  {
    id: "hg-culture-1",
    name: "노들섬 무료 공연",
    area: "한강",
    category: "culture",
    cost: 0,
    duration: 50,
    rating: 4.4,
    companions: ["solo", "friend", "couple", "family"],
    vibes: ["culture", "calm"],
    setting: "outdoor",
    bestStart: 19,
    tags: ["공연", "무료", "버스킹"],
    signal: { free: true },
    blurb: "주말 저녁 무료 버스킹·공연",
    emoji: "🎶",
  },

  // ───────── 북촌·종로 ─────────
  {
    id: "bc-culture-1",
    name: "국립현대미술관 서울",
    area: "북촌·종로",
    category: "culture",
    cost: 4000,
    duration: 80,
    rating: 4.7,
    companions: ["solo", "couple", "friend", "family"],
    vibes: ["culture", "calm"],
    setting: "indoor",
    bestStart: 11,
    tags: ["미술관", "전시", "데이트"],
    signal: { discount: 0, crowd: "mid" },
    blurb: "수요·토요일 야간 무료 개방",
    emoji: "🖼️",
  },
  {
    id: "bc-walk-1",
    name: "북촌한옥마을",
    area: "북촌·종로",
    category: "walk",
    cost: 0,
    duration: 60,
    rating: 4.6,
    companions: ["solo", "couple", "friend", "family"],
    vibes: ["calm", "culture"],
    setting: "outdoor",
    bestStart: 10,
    tags: ["한옥", "산책", "무료", "사진"],
    signal: { free: true },
    blurb: "골목마다 사진 명소인 한옥 산책",
    emoji: "🏯",
  },
  {
    id: "bc-food-1",
    name: "광장시장 먹거리",
    area: "북촌·종로",
    category: "food",
    cost: 9000,
    duration: 50,
    rating: 4.5,
    companions: ["friend", "couple", "family"],
    vibes: ["foodie"],
    setting: "indoor",
    bestStart: 12,
    tags: ["전통시장", "마약김밥", "빈대떡"],
    signal: { crowd: "high" },
    blurb: "마약김밥·빈대떡으로 즐기는 시장 투어",
    emoji: "🥟",
  },
  {
    id: "bc-cafe-1",
    name: "익선동 한옥카페",
    area: "북촌·종로",
    category: "cafe",
    cost: 7500,
    duration: 55,
    rating: 4.5,
    companions: ["couple", "friend"],
    vibes: ["calm", "trendy"],
    setting: "indoor",
    bestStart: 14,
    tags: ["한옥", "감성", "데이트"],
    blurb: "한옥을 개조한 익선동 감성 카페",
    emoji: "🍵",
  },
  {
    id: "bc-dessert-1",
    name: "종로 전통 빙수",
    area: "북촌·종로",
    category: "dessert",
    cost: 9500,
    duration: 40,
    rating: 4.4,
    companions: ["friend", "couple", "family"],
    vibes: ["foodie", "calm"],
    setting: "indoor",
    bestStart: 16,
    tags: ["빙수", "전통"],
    signal: { discount: 10 },
    blurb: "팥빙수 시즌 10% 할인",
    emoji: "🍧",
  },

  // ───────── 신사·압구정 ─────────
  {
    id: "ss-cafe-1",
    name: "가로수길 디저트카페",
    area: "신사·압구정",
    category: "cafe",
    cost: 9000,
    duration: 55,
    rating: 4.4,
    companions: ["couple", "friend"],
    vibes: ["trendy"],
    setting: "indoor",
    bestStart: 13,
    tags: ["디저트", "트렌디"],
    blurb: "가로수길 시그니처 디저트 카페",
    emoji: "🧁",
  },
  {
    id: "ss-shopping-1",
    name: "가로수길 편집숍 투어",
    area: "신사·압구정",
    category: "shopping",
    cost: 0,
    duration: 60,
    rating: 4.3,
    companions: ["friend", "couple", "solo"],
    vibes: ["trendy"],
    setting: "indoor",
    bestStart: 14,
    tags: ["쇼핑", "윈도쇼핑", "무료"],
    signal: { free: true },
    blurb: "구경만 해도 즐거운 편집숍 거리",
    emoji: "🛍️",
  },
  {
    id: "ss-food-1",
    name: "압구정 파스타",
    area: "신사·압구정",
    category: "food",
    cost: 16000,
    duration: 70,
    rating: 4.5,
    companions: ["couple", "friend"],
    vibes: ["foodie", "trendy"],
    setting: "indoor",
    bestStart: 12,
    tags: ["파스타", "데이트"],
    blurb: "분위기 좋은 압구정 이탈리안",
    emoji: "🍝",
  },
  {
    id: "ss-culture-1",
    name: "신사 미디어아트 전시",
    area: "신사·압구정",
    category: "culture",
    cost: 12000,
    duration: 70,
    rating: 4.5,
    companions: ["couple", "friend", "solo"],
    vibes: ["culture", "trendy"],
    setting: "indoor",
    bestStart: 15,
    tags: ["전시", "미디어아트", "포토존"],
    signal: { discount: 20, crowd: "mid" },
    blurb: "지금 선예매 20% 할인 중",
    emoji: "🌌",
  },
  {
    id: "ss-bar-1",
    name: "압구정 루프탑바",
    area: "신사·압구정",
    category: "bar",
    cost: 18000,
    duration: 80,
    rating: 4.6,
    companions: ["couple", "friend"],
    vibes: ["trendy", "calm"],
    setting: "outdoor",
    bestStart: 20,
    tags: ["루프탑", "야경"],
    blurb: "야경이 예쁜 루프탑 한 잔",
    emoji: "🌃",
  },

  // ───────── 잠실·송파 ─────────
  {
    id: "js-walk-1",
    name: "석촌호수 산책",
    area: "잠실·송파",
    category: "walk",
    cost: 0,
    duration: 50,
    rating: 4.6,
    companions: ["solo", "friend", "couple", "family"],
    vibes: ["calm", "active"],
    setting: "outdoor",
    bestStart: 17,
    tags: ["호수", "산책", "무료", "벚꽃"],
    signal: { free: true },
    blurb: "호수를 한 바퀴 도는 무료 힐링 산책",
    emoji: "🦢",
  },
  {
    id: "js-activity-1",
    name: "롯데월드 어드벤처",
    area: "잠실·송파",
    category: "activity",
    cost: 40000,
    duration: 180,
    rating: 4.5,
    companions: ["couple", "friend", "family"],
    vibes: ["active"],
    setting: "indoor",
    bestStart: 11,
    tags: ["놀이공원", "어트랙션"],
    signal: { discount: 25 },
    blurb: "현장 대비 25% 싼 온라인 특가",
    emoji: "🎢",
  },
  {
    id: "js-cafe-1",
    name: "송파 베이커리카페",
    area: "잠실·송파",
    category: "cafe",
    cost: 7000,
    duration: 50,
    rating: 4.3,
    companions: ["solo", "friend", "couple", "family"],
    vibes: ["calm"],
    setting: "indoor",
    bestStart: 13,
    tags: ["베이커리", "넓은좌석"],
    blurb: "좌석 넓어 오래 머물기 좋은 카페",
    emoji: "🥖",
  },
  {
    id: "js-food-1",
    name: "방이동 맛집거리",
    area: "잠실·송파",
    category: "food",
    cost: 12000,
    duration: 60,
    rating: 4.4,
    companions: ["friend", "couple", "family"],
    vibes: ["foodie"],
    setting: "indoor",
    bestStart: 18,
    tags: ["먹자골목", "가성비"],
    blurb: "선택지 많은 방이동 먹자골목",
    emoji: "🍲",
  },
  {
    id: "js-culture-1",
    name: "롯데타워 전망대",
    area: "잠실·송파",
    category: "culture",
    cost: 19000,
    duration: 70,
    rating: 4.5,
    companions: ["couple", "friend", "family"],
    vibes: ["trendy", "culture"],
    setting: "indoor",
    bestStart: 19,
    tags: ["전망대", "야경"],
    signal: { discount: 15 },
    blurb: "서울 야경 1등, 선예매 15% 할인",
    emoji: "🗼",
  },
];

export function placesByArea(area: string): Place[] {
  if (area === "auto") return PLACES;
  return PLACES.filter((p) => p.area === area);
}
